project_id = "icxlyynsvpfbmlrrqjyp"

[functions.isabella-chat]
verify_jwt = false

[functions.nubi-transaction]
verify_jwt = false

[functions.dreamspaces-api]
verify_jwt = false

[functions.kaos-audio]
verify_jwt = false

[functions.isabella-exports]
verify_jwt = false
